name: dog_pal
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  sentry: ^3.0.1
  shared_preferences: ^0.5.7+3
  flutter_screenutil: ^1.1.0  
  extended_image: ^0.8.0
  photo_view: ^0.9.2
  cloud_firestore_mocks: ^0.4.4
  connectivity: ^0.4.8+6
  flutter_staggered_animations:
    git:
      url: https://github.com/Hadii1/flutter_staggered_animations
  url_launcher: ^5.4.10
  shimmer: ^1.1.1
  google_maps_webservice: ^0.0.16
  firebase_storage: ^3.1.5
  permission_handler: ^5.0.0+hotfix.6  
  geolocator: ^5.3.1
  numberpicker: ^1.2.0
  multi_image_picker: ^4.6.7
  flutter_typeahead: ^1.8.1
  flutter_spinkit: ^4.1.2+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.5
  provider: ^4.1.2
  email_validator: ^1.0.0
  firebase_auth: ^0.16.0
  material_design_icons_flutter: ^4.0.5245    
  path_provider: ^1.6.9




  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2


dev_dependencies:
  build_runner: ^1.10.0
  mockito: ^4.1.1

  test: any

  
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter




flutter:
  assets:
    - assets/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300


    - family: Pacifico
      fonts:
        - asset : assets/fonts/Pacifico-Regular.ttf

  uses-material-design: true